### ISSUE TITLE
`/autopay` Command 

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#290] opened 2023-05-04 01:50 UTC
1. Add a new command `/autopay true|false` that enables/disables permit2 URL payouts for a particular issue.
2. The bot should respond with a success message
3. On issue close and `autopay == false` the bot should display a warning message of why a permit URL is not generated
4. Update help menu accordingly

Notice that there is the `auto-pay-mode` bot's param which enables/disables automatic payments for the whole org/repo. The `/autopay true|false` command should take precedence on the particular issue over the bot's config.

**Comment by pavlovcik** [comment] 2023-05-31 09:29
I think we should comment this out and re-enable when gnosis safe is ready. 

I also have concerns with the command name, perhaps something like `/autopay false` is more clear.

**Comment by rndquu** [comment] 2023-05-31 11:58
Ok, so this task is about the "autopay" command.

What should be done:
1. Add a new command `/autopay true|false` that enables/disables permit2 URL payouts for a particular issue.
2. The bot should respond with a success message
3. On issue close and `autopay = false` the bot should display a warning message of why a permit URL is not generated
4. Update help menu accordingly

Notice that there is the `auto-pay-mode` bot's param which enables/disables automatic payments for the whole org/repo. The `/autopay true|false` command should take precedence over the bot's config.

**Comment by pavlovcik** [comment] 2023-05-31 12:11
@rndquu @0xcodercrane @Steveantor please provide your inputs on the time estimate!

**Comment by seprintour** [comment] 2023-05-31 15:54
Can get this done

**Comment by seprintour** [comment] 2023-06-02 08:49
@0xcodercrane 

[chore: skip membership check](https://github.com/ubiquity/ubiquibot/commit/c8ed715d7960d4eda9fed17e384a53062006d3f8) broke the repo

It no longer starts, Error: 

```
const mdast_util_from_markdown_1 = require("mdast-util-from-markdown");
                                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module
```

**Comment by 0xcodercrane** [comment] 2023-06-02 09:18
> @0xcodercrane
> 
> [chore: skip membership check](https://github.com/ubiquity/ubiquibot/commit/c8ed715d7960d4eda9fed17e384a53062006d3f8) broke the repo, might not be this commit but the comment file is causing troubles
> 
> It no longer starts, Error:
> 
> ```
> const mdast_util_from_markdown_1 = require("mdast-util-from-markdown");
>                                    ^
> Error [ERR_REQUIRE_ESM]: require() of ES Module
> ```

Are you getting the error locally or staging?
https://github.com/ubiquibot/staging/issues/20
I am testing that feature on staging connected to `development` branch it looks fine

**Comment by seprintour** [comment] 2023-06-02 14:05
@0xcodercrane issue still persist.. i am commenting the file out as temp fix

**Comment by 0xcodercrane** [comment] 2023-06-03 13:56
> @0xcodercrane issue still persist.. i am commenting the file out as temp fix

Hmm you can comment it because that file shouldn't be a blocker to your issue. let me reenable it once fixed

**Comment by wannacfuture** [comment] 2023-06-04 02:16
@seprintour , how did u fixed the file temporarly? Did you fixed tsconfig.json or fixed files in lib folder?
Could you give me some information in detail about it?

**Comment by pavlovcik** [comment] 2023-06-04 04:07
It looks like they are referring to `mdast-util-from-markdown`

**Comment by 0xcodercrane** [comment] 2023-06-05 14:00
I am handing it over to @rndquu for a while. he has more context on it but i will jump in here after finishing the incentive issue on issue.

**Comment by 0xcodercrane** [comment] 2023-06-05 15:18
I was talking about the issue with `mdast-util-from-markdown` npm

**Comment by 0xcodercrane** [comment] 2023-06-06 02:01
The PR has an issue in runtime. 

```
Jun 6, 10:00:41 AM: INIT_START Runtime Version: nodejs:18.v7	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:26e9402591d9c467cdcc7355f843d61968f36ecb6e9ef5ab253cc21163343275Jun 6, 10:00:41 AM: 2023-06-06T02:00:41.422Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.MalformedHandlerName","errorMessage":"Bad handler","stack":["Runtime.MalformedHandlerName: Bad handler","    at _splitHandlerString (file:///var/runtime/index.mjs:900:15)","    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1031:36)","    at start (file:///var/runtime/index.mjs:1195:42)","    at file:///var/runtime/index.mjs:1201:7","    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"]}Jun 6, 10:00:41 AM: 2023-06-06T02:00:41.672Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.MalformedHandlerName","errorMessage":"Bad handler","stack":["Runtime.MalformedHandlerName: Bad handler","    at _splitHandlerString (file:///var/runtime/index.mjs:900:15)","    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1031:36)","    at start (file:///var/runtime/index.mjs:1195:42)","    at file:///var/runtime/index.mjs:1201:7","    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"]}Jun 6, 10:00:41 AM: Unknown application error occurred
Runtime.MalformedHandlerNameJun 6, 10:00:41 AM: 18a3be60 Duration: 198.22 ms	Memory Usage: 17 MB	
```

**Comment by seprintour** [comment] 2023-06-06 05:02
> The PR has an issue in runtime.
> 
> ```
> Jun 6, 10:00:41 AM: INIT_START Runtime Version: nodejs:18.v7	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:26e9402591d9c467cdcc7355f843d61968f36ecb6e9ef5ab253cc21163343275Jun 6, 10:00:41 AM: 2023-06-06T02:00:41.422Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.MalformedHandlerName","errorMessage":"Bad handler","stack":["Runtime.MalformedHandlerName: Bad handler","    at _splitHandlerString (file:///var/runtime/index.mjs:900:15)","    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1031:36)","    at start (file:///var/runtime/index.mjs:1195:42)","    at file:///var/runtime/index.mjs:1201:7","    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"]}Jun 6, 10:00:41 AM: 2023-06-06T02:00:41.672Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.MalformedHandlerName","errorMessage":"Bad handler","stack":["Runtime.MalformedHandlerName: Bad handler","    at _splitHandlerString (file:///var/runtime/index.mjs:900:15)","    at UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1031:36)","    at start (file:///var/runtime/index.mjs:1195:42)","    at file:///var/runtime/index.mjs:1201:7","    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"]}Jun 6, 10:00:41 AM: Unknown application error occurred
> Runtime.MalformedHandlerNameJun 6, 10:00:41 AM: 18a3be60 Duration: 198.22 ms	Memory Usage: 17 MB	
> ```

Hmm, what does a malformed handler on the lambda mean?. Confused

**Comment by pavlovcik** [comment] 2023-06-08 10:43
@Draeieg you should re-open the issue if it is confirmed to be not working.

**Comment by wannacfuture** [comment] 2023-06-08 17:25
can I assign this issue as it is reopened?

**Comment by rndquu** [comment] 2023-06-08 19:43
@0xcodercrane As far as I understand the PR for this issue was reverted 2 days ago because of the [netlify error](https://github.com/ubiquity/ubiquibot/issues/290#issuecomment-1577778908). You sure that the netlify issue is caused by this [PR](https://github.com/ubiquity/ubiquibot/pull/363)?

**Comment by seprintour** [comment] 2023-06-08 19:56
I think its wrong to reopen issues, several issues have been reopened just because they probably wasn't setup correctly.

The netlify error for this, i lack enough context.. doesn't look like i have seen anything like nor do i know why it occurred.. but all i know is the code works and there's no errors from my end

**Comment by seprintour** [comment] 2023-06-08 19:57
I guess the `logger` would help in most of these QA.. to see what is going on and where or how it breaks

**Comment by rndquu** [comment] 2023-06-08 20:04
> can I assign this issue as it is reopened? Can be done in an hour.

This issue is already implemented, we just need to fix some minor devops errors

**Comment by rndquu** [comment] 2023-06-08 20:12
> I think its wrong to reopen issues, several issues have been reopened just because they probably wasn't setup correctly.
> 
> The netlify error for this, i lack enough context.. doesn't look like i have seen anything like nor do i know why it occurred.. but all i know is the code works and there's no errors from my end

@seprintour 

It's fine to reopen issues if they are not working as expected. In this particular case the issue seems to be [on our end](https://github.com/ubiquity/ubiquibot/issues/290#issuecomment-1577778908).

Could you reopen the PR for the [autopay feature](https://github.com/ubiquity/ubiquibot/issues/290)? I will try to reproduce the netlify error.

**Comment by 0xcodercrane** [comment] 2023-06-09 08:26
> @0xcodercrane As far as I understand the PR for this issue was reverted 2 days ago because of the [netlify error](https://github.com/ubiquity/ubiquibot/issues/290#issuecomment-1577778908). You sure that the netlify issue is caused by this [PR](https://github.com/ubiquity/ubiquibot/pull/363)?

Sure

**Comment by 0xcodercrane** [comment] 2023-06-09 08:29
> can I assign this issue as it is reopened? Can be done in an hour.

I guess @seprintour will wrap it up if we give him more context about debugging

**Comment by Steveantor** [comment] 2023-06-09 09:30
> > I think its wrong to reopen issues, several issues have been reopened just because they probably wasn't setup correctly.
> > The netlify error for this, i lack enough context.. doesn't look like i have seen anything like nor do i know why it occurred.. but all i know is the code works and there's no errors from my end
> 
> @seprintour
> 
> It's fine to reopen issues if they are not working as expected. In this particular case the issue seems to be [on our end](https://github.com/ubiquity/ubiquibot/issues/290#issuecomment-1577778908).
> 
> Could you reopen the PR for the [autopay feature](https://github.com/ubiquity/ubiquibot/issues/290)? I will try to reproduce the netlify error.

Reopening issues is messy, we should open QA issues instead

**Comment by pavlovcik** [comment] 2023-06-10 06:42
I like the idea of reopening an existing issue because the entire conversation is in one place vs having to cross reference issues. So I argue that its actually messier to open new issues. 

Beyond that, as far as I understand, the payment permit can not possibly be regenerated for a re-opened issue which helps safeguard against infinite pay for a single poorly implemented bounty.

I am happy to discuss and debate standard process improvements though.

**Comment by pavlovcik** [comment] 2023-07-06 10:37
@Draeieg can you confirm this is done by marking it as completed?

**Comment by pavlovcik** [comment] 2023-07-30 08:34
@Draeieg a follow up

**Comment by Draeieg** [comment] 2023-08-03 21:52
> @Draeieg a follow up. @wannacfuture there seems to be confusion around the status of this issue. You can see the linked pull request for the context. Would you be able to get this one closed out before it turns into a bigger mess?

this is currently broken, it got commented out while we get a fix in #353

**Comment by wannacfuture** [comment] 2023-08-04 03:51
yeah, can be closed.

**Comment by pavlovcik** [comment] 2023-08-04 04:21
> Would you be able to get this one closed out before it turns into a bigger mess?

> this is currently broken, it got commented out while we get a fix in #353

What I mean is to solve the problem and then close the issue. Not just to close the issue without solving the problem.

**Comment by wannacfuture** [comment] 2023-08-04 04:52
> What I mean is to solve the problem and then close the issue. Not just to close the issue without solving the problem.

Sorry, lol. Yeah, Just took a look at this. Do you suggest autopay info for an issue to the DB or just checking comments on the issue?

**Comment by pavlovcik** [comment] 2023-08-04 05:00
I like the idea of depending as much as possible on GitHub comments but other team members have expressed concerns about rate limits (I don't think it's an issue)

@Rndquu rfc

**Comment by rndquu** [comment] 2023-08-04 23:05
> I like the idea of depending as much as possible on GitHub comments but other team members have expressed concerns about rate limits (I don't think rate limits are an issue)
> 
> @rndquu rfc

For this particular `/autopay` command it is simpler to parse issue's comments (as it is already implemented here https://github.com/ubiquity/ubiquibot/pull/579)

**Closed** 2023-08-09 16:18 UTC
Labels: Time: <1 Day, Priority: 2 (High), Permitted, Price: 450 USD
