### ISSUE TITLE
AI: Check for Duplicate Specs

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/ubiquibot#488] opened 2023-07-11 04:36 UTC
# Simplified Specification

Derived from the conversation comment [here](https://github.com/ubiquity/ubiquibot/issues/488#issuecomment-1668927166). 

We could do things without a vector database in order to simplify things, here's how: 

1. A new issue is posted
2. We ask ChatGPT to extract a word list of the most "important" (i.e. unique adjectives?) words (for example, when I wanted to find this issue, I searched for the term "duplicate")
3. We search the repository for all issues with the important words
4. We go from highest issue number (most recent) and read the specification. 
5. If >80% confidence, stop the search and link back to it with a warning saying that it's likely to be a duplicate. 

This approach might be a little more brittle (rate limits) but we won't have to worry about the database which should make implementation and maintenance much easier.

# Original Specification (for reference only, do not use)

### Overview

As part of our AI roadmap, we want to [prevent duplicate issues](https://github.com/ubiquity/ubiquibot/discussions/107#discussioncomment-4945998).

The idea is to have:
1. an event handler for creating a new issue 
2. that passes the issue specification to ChatGPT (asynchronously/slowly is fine)
3. have a cache "vector database" of issue similarity within the same repository only
4. have a `ubiquibot-config` property with a `issue-similarity-confidence-threshold: float`

Then with an issue similarity confidence threshold of e.g. `0.8` that means that if the bot is 80% confident it's a redundant issue. It will then post a comment that will explain it is X% confident that this is a redundant issue and backlink the redundant issue in question.

### Remarks

- This should be broken down further but will put a broad `Time: <1 Week` for anybody particularly motivated to get started with it. 
- I'm not sure about the relationship with ChatGPT and the vector database, but from what I understand, vector database is good for evaluating similarity between things and ChatGPT is a good interpretation engine. 

### Context

              Duplicate 

- https://github.com/ubiquity/ubiquibot/issues/477

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/issues/406#issuecomment-1630097779_

**Comment by b4s36t4** [comment] 2023-07-11 20:44
@pavlovcik Maybe following this works? https://docs.pinecone.io/docs/langchain

We're gonna index every issue when there's a new issue event got, then we do similarity_search based on the score of the search we do relevant work, this flow seems ok?

**Comment by b4s36t4** [comment] 2023-07-12 08:34
I think we don't have to use langchain here because all we're doing is smiliarity search, I don't think even using openAI's API would need here. All I'm thinking is just index the issue first then do the similarity search on issue and based on score we do action.

**Comment by b4s36t4** [comment] 2023-07-12 08:34
I just mentioned blog because we get to see how the similarity search is being used.

**Comment by seprintour** [comment] 2023-07-26 17:27
> I've heard some recent mixed reviews on using langchain in any serious production software (it seems that it's only suitable for small hobby projects from what I heard) so I would need to think on this longer before approving the approach.

I think we can make use of pre-trained language models and a python script to setup an API for this. we won't have to pay for anything apart from using the server which i assume is already available.

There's a model from Google and it should work pretty well

**Comment by seprintour** [comment] 2023-07-26 19:42
![Screenshot 2023-07-26 at 8 41 53 PM](https://github.com/ubiquity/ubiquibot/assets/51956013/f7996adc-b31b-4817-b362-564021d6346d)

Compiling a test code with the dataset with text `All Commands Should be in Beginning of Comment` and `All Commands Need Strict Parsers` and here's the similiarity confidence

**Comment by seprintour** [comment] 2023-07-26 19:44
![Screenshot 2023-07-26 at 8 43 50 PM](https://github.com/ubiquity/ubiquibot/assets/51956013/89b15ed8-524c-4cb6-961c-448ba09bee2a)

Almost same confidence between #289 and #424

**Comment by pavlovcik** [comment] 2023-07-28 04:27
Reposting on behalf of a friend

> Yea, like b4s36t4 said, similarity search. Standard approach is transform the text to TF-IDF vectors, then compute some similarity metric over the vectors (like: https://stackoverflow.com/a/8897648); doc pair w/ higher similarity score ==> more likely dup issue.

**Comment by b4s36t4** [comment] 2023-07-28 04:55
What do you suggest @pavlovcik ? Using a vectordb or sckit to do a similarity search?

**Comment by pavlovcik** [comment] 2023-07-28 04:57
I'm asking for some more opinions from friends with a lot of experience with this type of work before deciding. But my thoughts are:

My only hesitation with this approach is bloating our tech stack with python and it’s libraries instead of just running everything through ChatGPT. 

It could simplify maintenance if we just use ChatGPT for our “thinking” engine?

**Comment by whilefoo** [comment] 2023-07-28 18:18
I told ChatGPT to compare two Github issues and determine if they are duplicates: https://chat.openai.com/share/5bbdcd21-db31-4ead-b4d1-9e916d5e2cd7

While it accurately said that they are not duplicates, it couldn't tell me the probability in terms of percentage.

**Comment by pavlovcik** [comment] 2023-07-30 02:41
More from my friend:

> Or “buy” instead of build?: https://github.com/marketplace/actions/issues-similarity-analysis same: https://github.com/actions-cool/issues-similarity-analysis

> Or here’s pretty much the non-ChatGPT solution I was talking about: https://github.com/pawl/github_issue_similarity/blob/master/main.py 

> IDK why he complicated and slowed it by using a SQLite db, but pip install the dependencies, fill in the GH token, and you should be able to just run that script… (maybe, I just glanced at this script, plus it’s 6y old…)

**Comment by seprintour** [comment] 2023-07-30 03:51
> More from my friend:
> 
> > Or “buy” instead of build?: https://github.com/marketplace/actions/issues-similarity-analysis same: https://github.com/actions-cool/issues-similarity-analysis
> 
> > Or here’s pretty much the non-ChatGPT solution I was talking about: https://github.com/pawl/github_issue_similarity/blob/master/main.py
> 
> > IDK why he complicated and slowed it by using a SQLite db, but pip install the dependencies, fill in the GH token, and you should be able to just run that script… (maybe, I just glanced at this script, plus it’s 6y old…)

I just went through this https://github.com/marketplace/actions/issues-similarity-analysis and it makes use of the [Compare Similiarity](https://www.npmjs.com/package/compare-similarity) package so we can just implement that in our code without installing the app

But i do not think it is smart enough to be used in production, because it only works with directly similiar texts.. it does not understand when synonyms of same word is used which is important

**Comment by seprintour** [comment] 2023-07-30 03:53
> Or here’s pretty much the non-ChatGPT solution I was talking about: https://github.com/pawl/github_issue_similarity/blob/master/main.py

This is the same thing i was talking about here https://github.com/ubiquity/ubiquibot/issues/488#issuecomment-1652223433 but with a dictionary

**Comment by pavlovcik** [comment] 2023-07-30 04:29
> But i do not think it is smart enough to be used in production, because it only works with directly similiar texts.. it does not understand when synonyms of same word is used which is important

> but with a dictionary

This makes me more convinced about using ChatGPT for text recognition. Their model is superior to anything else available, and it's maintained/updated.

**Comment by seprintour** [comment] 2023-07-30 04:44
> > But i do not think it is smart enough to be used in production, because it only works with directly similiar texts.. it does not understand when synonyms of same word is used which is important
> 
> > but with a dictionary
> 
> This makes me more convinced about using ChatGPT for text recognition. Their GPT-4 model is superior to anything else available, and it's maintained/updated.
> 
> If I recall correctly we can send 50 requests per every three hours. If each organization has its own OpenAI API key, this should be more than sufficient from a rate limit perspective.
> 
> New issues are not created that frequently.

Yea, the issue is they do not give access to ChatGPT doing arithmetics like the percentage of similarity.. it just says if it is or not, if that is enough right now we can build around it or look for an alternative that provides a percentage

**Comment by pavlovcik** [comment] 2023-07-30 05:39
> Yea, the issue is they do not give access to ChatGPT doing arithmetics like the percentage of similarity..

I'm quite certain that some prompt engineering can solve this. 

> Also, won't organizations need an account with GPT4 active to use the API?

Yes can use my personal account to start. However for development I would expect that a bounty hunter can use their own account.

**Comment by seprintour** [comment] 2023-07-30 06:06
> > Yea, the issue is they do not give access to ChatGPT doing arithmetics like the percentage of similarity..
> 
> I'm quite certain that some prompt engineering can solve this.
> 
> > Also, won't organizations need an account with GPT4 active to use the API?
> 
> Yes can use my personal account to start. However for development I would expect that a bounty hunter can use their own account.

Yea, this makes sense..  I think we can find our way around it like you said, would have to play around with prompts to see something that works

I don't believe it can't respond with similiarity, i think its just mildly blocked

**Comment by ByteBallet** [comment] 2023-08-01 02:55
Vector database is usually used for measuring similarity between docs and query. So I think it is possible to make a this kind of similarity measurer. I want to be assigned to this task since https://github.com/ubiquity/ubiquibot/issues/511 is not started yet...

**Comment by ByteBallet** [comment] 2023-08-01 09:03
> I'm asking for some more opinions from friends with a lot of experience with this type of work before deciding. But my thoughts are:
> 
> My only hesitation with this approach is bloating our tech stack with python and it’s libraries instead of just running everything through ChatGPT.
> 
> It could simplify maintenance if we just use ChatGPT for our “thinking” engine?

Isn't it possible to use python back-end? If you all hate this solution, I can have a look on using langchain in typescript.
https://blog.langchain.dev/typescript-support/
I think this will take me about 10 days to complete perfectly.

**Comment by ByteBallet** [comment] 2023-08-01 09:16
The requirement for this issue is somehow straightforward. Just store all the issues to Vectorstore like Pinecone and each time the issue is created, compare the store to new issue and if the similarity is over threshold, post a comment. If you add timeline in this issue, I can start work right now.

**Comment by pavlovcik** [comment] 2023-08-08 05:22
We could do things without a vector database in order to simplify things, here's how: 

1. A new issue is posted
2. We ask ChatGPT to extract a word list of the most important words (for example, when I wanted to find this issue, I searched for the term "duplicate")
3. We search the repository for all issues with the important words
4. We go from highest issue number (most recent) and read the specification. 
5. If >80% confidence, stop the search and link back to it with a warning saying that it's likely to be a duplicate. 

This approach might be a little more brittle (rate limits) but we won't have to worry about the database which should make implementation and maintenance much easier.

**Comment by ByteBallet** [comment] 2023-08-08 05:29
> We could do things without a vector database in order to simplify things, here's how:
> 
> 1. A new issue is posted
> 2. We ask ChatGPT to extract a word list of the most "important" (i.e. unique adjectives?) words (for example, when I wanted to find this issue, I searched for the term "duplicate")
> 3. We search the repository for all issues with the important words
> 4. We go from highest issue number (most recent) and read the specification.
> 5. If >80% confidence, stop the search and link back to it with a warning saying that it's likely to be a duplicate.
> 
> This approach might be a little more brittle (rate limits) but we won't have to worry about the database which should make implementation and maintenance much easier.
> 
> @ByteBallet what do you think about this approach?

It makes sense. I think it is possible to address this issue with this methodology.

**Comment by pavlovcik** [comment] 2023-08-08 05:34
Let me experiment with some prompts. I generally like to provide additional context to GPT for better results.

**Comment by ByteBallet** [comment] 2023-08-08 05:36
> Let me experiment with some prompts. I generally like to provide additional context to GPT for better results. I should know within 15 minutes.

I will also try that.

**Comment by pavlovcik** [comment] 2023-08-08 05:40
Check out this conversation and its prompt: https://chat.openai.com/share/738e5b55-fbf2-412c-ac94-8ec586af5e62

**Comment by ByteBallet** [comment] 2023-08-08 05:43
Did you ignore all the comments?

**Comment by pavlovcik** [comment] 2023-08-08 05:44
Yes I ignored the conversation. I think that we should only consider the original issue specification comment.

**Comment by b4s36t4** [comment] 2023-08-08 05:45
I don't feel this could be right, this might produce the wrong results... Maybe not be the same we wants. 

We simply cannot figure the duplication based on the issue title, along with the description would give better results but that's another headache with the implementation.

**Comment by b4s36t4** [comment] 2023-08-08 05:46
@pavlovcik you don't want to use the vetcor database at all? Or you don't want to include python into the current tech stack?

**Comment by pavlovcik** [comment] 2023-08-08 05:48
> issue title, along with the description

It is using the issue title and the description. 

>  don't want to use the vetcor database at all? Or you don't want to include python

I want to minimize external dependencies and stack bloat in order to optimize for code maintainability among many new contributors.

**Comment by ByteBallet** [comment] 2023-08-08 05:50
> I don't feel this could be right, this might produce the wrong results... Maybe not be the same we wants.
> 
I think this kind of approach makes sense...

**Comment by ByteBallet** [comment] 2023-08-08 05:50
But the problem I think is in case of description is not sufficient...

**Comment by whilefoo** [comment] 2023-08-08 05:54
While I agree the approach with extracting important words won't be the most accurate, it simplifies things a lot. Vector database and natural language processing, according to my research, isn't easy to setup and it requires specialised knowledge.

> Check out this conversation and its prompt: https://chat.openai.com/share/738e5b55-fbf2-412c-ac94-8ec586af5e62

We should instruct ChatGPT to output the words in a specific format so we can parse it more easily.

**Comment by ByteBallet** [comment] 2023-08-08 05:58
> While I agree the approach with extracting important words won't be the most accurate, it simplifies things a lot. Vector database and natural language processing, according to my research, isn't easy to setup and it requires specialised knowledge.
> 
> > Check out this conversation and its prompt: https://chat.openai.com/share/738e5b55-fbf2-412c-ac94-8ec586af5e62
> 
> We should instruct ChatGPT to output the words in a specific format so we can parse it more easily.

I definitely agree with you, @whilefoo. If accuracy is prior we can use vector store, otherwise we can just use ChatGPT.

**Comment by pavlovcik** [comment] 2023-08-08 06:07
I want to prioritize making the codebase easy to maintain first. If the solution is inadequate regarding its accuracy, then we can look into a more advanced/robust implementation.

**Comment by ByteBallet** [comment] 2023-08-08 06:12
> However, because this approach emulates how a human (i.e. me) would search for duplicates, I think it will work most (i.e. close to 100%) of the time.
Is this true, though???

**Comment by pavlovcik** [comment] 2023-08-08 06:14
> Is this true, though???

Yes.

- I had a "duplicate issue" in my mind, which is my memory of this current (#488) issue. 
- To find it, I searched for the term "duplicate" 
- I started from the top (the highest issue number)
- Then went to the next one
- The content matches my memory with a high degree of confidence
- Match found.

**Comment by ByteBallet** [comment] 2023-08-08 07:56
I think there might be not so long description of issue that can exceed limit of ChatGPT, right?

**Comment by ByteBallet** [comment] 2023-08-11 05:49
Just sent a pull request. Looking forward to the feedback.
Thanks

**Closed** 2023-08-27 13:21 UTC
Labels: Time: <1 Week, Priority: 3 (High), Price: 900 USD
